import { CSVImporter } from '../CSVImporter';

describe('CSVImporter.parseCSVWithMeta', () => {
    it('returns rows and an empty meta for legacy CSVs (no comment line)', () => {
        const text = [
            'start_frame,end_frame,behavior',
            '10,20,sniffing',
            '30,42,licking_body',
        ].join('\n');

        const { rows, meta } = CSVImporter.parseCSVWithMeta(text);

        expect(rows).toHaveLength(2);
        expect(rows[0]).toMatchObject({ startFrame: 10, endFrame: 20, behavior: 'sniffing' });
        expect(rows[1]).toMatchObject({ startFrame: 30, endFrame: 42, behavior: 'licking_body' });
        expect(meta.behaviorShortcuts.size).toBe(0);
    });

    it('parses behavior→shortcut bindings from a `# trace-meta:` line', () => {
        const text = [
            '# trace-meta: behaviors=sniffing:s,licking_mouth_facial:l,nursing:n',
            'start_frame,end_frame,behavior',
            '10,20,sniffing',
        ].join('\n');

        const { rows, meta } = CSVImporter.parseCSVWithMeta(text);

        expect(rows).toHaveLength(1);
        expect(meta.behaviorShortcuts.get('sniffing')).toBe('s');
        expect(meta.behaviorShortcuts.get('licking_mouth_facial')).toBe('l');
        expect(meta.behaviorShortcuts.get('nursing')).toBe('n');
    });

    it('tolerates other comment lines before the header', () => {
        const text = [
            '# generated by trace v0.42 on 2026-05-04',
            '# trace-meta: behaviors=walking:w',
            '# additional notes about this labeling go here',
            'start_frame,end_frame,behavior',
            '0,15,walking',
        ].join('\n');

        const { rows, meta } = CSVImporter.parseCSVWithMeta(text);

        expect(rows).toHaveLength(1);
        expect(rows[0].behavior).toBe('walking');
        expect(meta.behaviorShortcuts.get('walking')).toBe('w');
    });

    it('round-trips URL-encoded names (defensive against commas/colons)', () => {
        // A behavior name with a comma in it would otherwise break the
        // pair-separator on the metadata line — encoding shields us.
        const encoded = encodeURIComponent('weird, name');
        const text = [
            `# trace-meta: behaviors=${encoded}:x,plain:p`,
            'start_frame,end_frame,behavior',
            '0,5,plain',
        ].join('\n');

        const { meta } = CSVImporter.parseCSVWithMeta(text);

        expect(meta.behaviorShortcuts.get('weird, name')).toBe('x');
        expect(meta.behaviorShortcuts.get('plain')).toBe('p');
    });

    it('ignores unknown metadata keys so the format can grow', () => {
        const text = [
            '# trace-meta: behaviors=sniffing:s notes=ignored future_key=42',
            'start_frame,end_frame,behavior',
            '0,5,sniffing',
        ].join('\n');

        const { meta } = CSVImporter.parseCSVWithMeta(text);

        expect(meta.behaviorShortcuts.size).toBe(1);
        expect(meta.behaviorShortcuts.get('sniffing')).toBe('s');
    });
});

describe('CSVImporter.parseCSV (back-compat shim)', () => {
    it('still returns plain rows for callers that don\'t need meta', () => {
        const text = [
            '# trace-meta: behaviors=walking:w',
            'start_frame,end_frame,behavior',
            '0,5,walking',
        ].join('\n');

        const rows = CSVImporter.parseCSV(text);

        expect(rows).toHaveLength(1);
        expect(rows[0]).toMatchObject({ startFrame: 0, endFrame: 5, behavior: 'walking' });
    });
});
